INSERT INTO MYAPP.MEMBER_PROFILE_IMG (IMG_IDX, IMG_FILE_NAME, MEM_ID) VALUES (2, 'jeongsoo12_123.jpg', 'jeongsoo12');
INSERT INTO MYAPP.MEMBER_PROFILE_IMG (IMG_IDX, IMG_FILE_NAME, MEM_ID) VALUES (3, 'jeongsoo13_123.jpg', 'jeongsoo13');
